# Generated by Django 2.1.1 on 2018-09-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Title', models.CharField(max_length=100)),
                ('Book_Author', models.CharField(max_length=100)),
                ('Book_Genre', models.CharField(max_length=100)),
                ('Book_Price', models.CharField(max_length=100)),
                ('Book_Rating', models.CharField(max_length=100)),
                ('Book_Date', models.CharField(max_length=100)),
            ],
        ),
    ]
